### ISSUE TITLE
error 404 on Link 2 demo 

### ISSUE THREAD

**Issue by Buliwyfa** [sjaakp/yii2-wysiwyg#1]
The link to demo:
https://sjaakpriester.nl/software/yii2-wysiwyg

gives an error:

Not Found (#404)

**Comment by sjaakp** [comment]
Hello Buliwyfa,

 

Correct link is: https://sjaakpriester.nl/software/wysiwyg.

Where did you get this link?

 

Thanks

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: Buliwyfa <notifications@github.com> 
Verzonden: zaterdag 8 februari 2020 18:06
Aan: sjaakp/yii2-wysiwyg <yii2-wysiwyg@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [sjaakp/yii2-wysiwyg] error 404 on Link 2 demo (#1)

 

The link to demo:
https://sjaakpriester.nl/software/yii2-wysiwyg

gives an error:

Not Found (#404)

**Comment by Buliwyfa** [comment]
on readme.md.

I create a pull request with the link fixed ;D
